authentication/urls.py
from django.urls import path
from .views import *


app_name = "authentication"

urlpatterns = [
    path('student/register', RegisterStudentView.as_view(), name='student-register'),
    path('student/profile/update/', EditStudentProfileView.as_view(), name='student-profile-update'),
    path('instructor/register', RegisterInstructorView.as_view(), name='instructor-register'),
    path('instructor/profile/update/', EditInstructorProfileView.as_view(), name='instructor-profile-update'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

core/urls.py
from django.urls import path
from .views import (
HomeView,
ExamView,
CourseView,
CourseCreateView,
course_single,
AssignmentCreateView,
AssignmentView,
AssignmentDeleteView,
ExamCreateView,
ExamListView,
AssignmentSubmissionView,
ExamDeleteView,
ExamSubmissionView,
ExamSubmissionListView,
AssignmentSubmissionListView,
AssignmentSubmissionDelete,
ExamSubmissionDelete

)
from django.conf import settings
from django.conf.urls.static import static

app_name = "core"

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),
                  path('exam/', ExamView.as_view(), name='exam'),
                  path('course/', CourseView.as_view(), name='course'),
                  path('course-create/', CourseCreateView.as_view(), name='course-create'),
                  path('assignment-create/', AssignmentCreateView.as_view(), name='assignment-create'),
                  path('assignment/', AssignmentView.as_view(), name='assignment-list'),
                  path('<pk>/delete/', AssignmentDeleteView.as_view(), name='delete-assignment'),
                  path('<int:id>/course-view/', course_single, name='course-view'),
                  path('exam-create/', ExamCreateView.as_view(), name='exam-create'),
                  path('exam-list/', ExamListView.as_view(), name='exam-list'),
                  path('<pk>/delete/', ExamDeleteView.as_view(), name='delete-exam'),
                  path('assignment-submission/', AssignmentSubmissionView.as_view(), name='assignment-submission'),
                  path('exam-submission/', ExamSubmissionView.as_view(), name='exam-submission'),
                  path('exam-submission-list/', ExamSubmissionListView.as_view(), name='exam-submission-list'),
                  path('assignment-submission-list/', AssignmentSubmissionListView.as_view(), name='assignment-submission-list'),
                  path('<pk>/delete/', AssignmentSubmissionDelete.as_view(), name='assignment-submission-delete'),
                  path('<pk>/delete/', ExamSubmissionDelete.as_view(), name='exam-submission-delete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab_exam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('core.urls', namespace='core')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="description" content="Dento - Dentist &amp; Medical HTML Template">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Title -->
  <title>Online Lab {% block title %} {% endblock %}</title>

  <!-- Favicon -->
  <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

  <!-- Core Stylesheet -->
  <link rel="stylesheet" href="{% static 'style.css' %}">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    {% block styles %} {% endblock %}

</head>

<body>
   {% include 'nav.html' %}


       {% block content %}
      {% endblock %}




   <footer class="footer-area bg-img bg-gradient-overlay">
    <div class="container">
      <div class="row">
        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg-6">
          <div class="single-footer-widget">
            <a href="/" class="d-block mb-4"><img style="height: 30px" src="{% static 'logo1.png' %}" alt=""></a>

            <div class="footer-contact">
                 <p> We Believe Everyone Should Have Easy Access To Online</p>
              <p> Dhaka, Bangladesh</p>
              <p> +88 01798128...</p>
              <p> info.onlinelab@gmail.com</p>
            </div>
          </div>
        </div>

        <!-- Single Footer Widget -->




        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <!-- Widget Title -->
            <h5 class="widget-title">Newsletter</h5>

            <p>We will send out weekly newest article and some great offers</p>
            <!-- Newsletter Form -->
            <div class="footer-newsletter-form">
              <form action="#" method="post">
                <input type="email" name="nl-email" value="" placeholder="Email Address">
                <button type="submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
              </form>
            </div>

            <!-- Social Info -->
            <div class="footer-social-info">
              <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Google Plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Linkedin"><i class="fa fa-linkedin"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Copywrite Area -->
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="copywrite-content">
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://docmed.com" target="_blank">OnlineLab</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- ***** Footer Area End ***** -->

  <!-- ******* All JS ******* -->
  <!-- jQuery js -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Popper js -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap js -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- All js -->
  <script src="{% static 'js/dento.bundle.js' %}"></script>
  <!-- Active js -->
  <script src="{% static 'js/default-assets/active.js' %}"></script>


   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

   {% block javascripts %} {% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Home{% endblock %}


{% block content %}

    <!-- ***** Welcome Area Start ***** -->
  <section class="welcome-area">
    <!-- Welcome Slides -->
    <div class="welcome-slides owl-carousel">
      <!-- Single Welcome Slide -->
      <div class="welcome-welcome-slide bg-img bg-gradient-overlay jarallax"  style="background-image: url('{% static 'img/img1.jpg' %}');">
        <div class="container h-100">
          <div class="row h-100 align-items-center">

<div class="col-12">
              <!-- Welcome Text -->
              <div class="welcome-text text-center">
                <h2 data-animation="fadeInUp" data-delay="100ms"></h2>

              </div>

            </div>
          </div>
        </div>
      </div>

      <!-- Single Welcome Slide -->
      <div class="welcome-welcome-slide bg-img bg-gradient-overlay jarallax"  style="background-image: url('{% static 'img/img2.jpg' %}');">
        <div class="container h-100">
          <div class="row h-100 align-items-center">
              <div class="col-12">
              <!-- Welcome Text -->
              <div class="welcome-text text-center">
                <h2 data-animation="fadeInUp" data-delay="100ms"></h2>

              </div>


            </div>
          </div>
        </div>
      </div>
    </div>
  </section>



    <section class="dentist-area section-padding-35-0">

        <div class="container">



            <div class="row">

                <div class="col-12">
                    <div class="section-heading text-center">
                         </br>

                        <h3 class="lead">Available Courses </h3>
                        <div class="line"></div>
                    </div>
                </div>
            </div>

            <div class="row">
          {% for course in course %}
        <!-- Single Dentist Area -->
        <div class="col-12 col-sm-6 col-md-4">

          <div class="single-dentist-area mb-100">
            <img  style="height: 300px; width: 500px " src="{{ course.course_image.url }}" alt="">
            <!-- Dentist Content -->
            <div class="dentist-content">
              <!-- Social Info -->
              <div class="dentist-social-info">

              </div>
              <!-- Dentist Info -->
              <div class="dentist-info bg-gradient-overlay">
                <h5>{{ course.course_name }} |  <a href="{% url 'core:course-view' course.id %}"> <small>VIEW COURSE</small></a> </h5>
                <p>{{ course.teacher_name }} </p>


              </div>
            </div>
          </div>
                    </div>
                {% endfor %}


                <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
                </div>


            </div>

        </div>
    </section>

{% endblock %}

templates/nav.html
{% load static %}
<!-- Preloader -->
<!-- Preloader -->


<div id="preloader">
    <div class="preload-content">
        <div id="dento-load"></div>
    </div>
</div>

<!-- ***** Header Area Start ***** -->
<header class="header-area">
    <!-- Top Header Area -->
    <div class="top-header-area">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <!-- Top Content -->
                <div class="col-6 col-md-9 col-lg-8">
                    <div class="top-header-content">
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Dhaka, Bangladesh"><i
                                class="fa fa-map-marker"></i> <span>Dhaka, Bangladesh</span></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="info.docmed@gmail.com"><i
                                class="fa fa-envelope"></i> <span>info.onlineLab@gmail.com</span></a>
                    </div>
                </div>
                <!-- Top Header Social Info -->
                <div class="col-6 col-md-3 col-lg-4">
                    <div class="top-header-social-info text-right">
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i
                                class="fa fa-facebook"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i
                                class="fa fa-twitter"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i
                                class="fa fa-google-plus"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Linkedin"><i
                                class="fa fa-linkedin"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i
                                class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Top Header End -->

    <!-- Main Header Start -->
    <div class="main-header-area">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">
                <!-- Classy Menu -->
                <nav class="classy-navbar justify-content-between" id="dentoNav">

                    <!-- Logo -->
                    <a class="nav-brand" href=""><img style="height: 30px" src="{% static 'logo1.png' %}" alt="">
                    </a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- Close Button -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">


                            <ul id="nav">

                                <li><a href="/">Home</a></li>

                                {% if request.user.is_authenticated and request.user.role == 'instructor' %}

                                    <li>
                                        <a href="">
                                            <span class="glyphicon glyphicon-user">
                                                    {{ request.user.first_name }}
                                            </span>
                                        </a>
                                        <ul class="dropdown">
                                            <li><a href="{% url 'authentication:instructor-profile-update' %}"> Edit Profile</a></li>
                                            <li><a href="{% url 'core:course' %}">Courses</a></li>
                                            <li><a href="{% url 'core:course-create' %}"> Create Course</a></li>
                                            <li><a href="{% url 'core:exam-submission-list' %}"> Exam Submissions</a></li>
                                            <li><a href="{% url 'core:assignment-submission-list' %}"> Assignment Submissions</a></li>
                                            <li><a href="{% url 'authentication:logout' %}"> Logout</a></li>

                                        </ul>
                                    </li>


                             {% elif request.user.is_authenticated and request.user.role == 'student' %}
                                     <li><a href="{% url 'core:course' %}">Courses</a></li>

                                    <li>
                                        <a href="">
                                            <span class="glyphicon glyphicon-user">
                                                    {{ request.user.first_name }}
                                            </span>
                                        </a>
                                        <ul class="dropdown">

                                            <li><a href="{% url 'authentication:student-profile-update' %}"> Edit Profile</a></li>
                                            <li><a href="{% url 'authentication:logout' %}"> Logout</a></li>

                                        </ul>
                                    </li>




                                {% else %}
                                    <li><a href="#">Register</a>
                                        <ul class="dropdown">
                                            <li><a href="{% url 'authentication:instructor-register' %}"> INSTRUCTOR</a></li>
                                            <li><a href="{% url 'authentication:student-register' %}"> STUDENT</a></li>
                                        </ul>
                                    </li>

                                    <li>
                                        <a href="{% url 'authentication:login' %}">
                                            <span class="glyphicon glyphicon-user"> Login</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>

                        </div>
                        <!-- Nav End -->
                    </div>

                    <!-- Booking Now Button -->


                </nav>
            </div>
        </div>
    </div>
</header>